---
- name: CONFIGURAR DIRECCIONAMIENTO IPv4
  hosts: csr1kv
  gather_facts: false
  connection: local
  tasks:
    - name: SET IPv4 ADDRESS
      ios_config:
        parents: "Interface GigabitEthernet2"
        lines:
          - description IPv4 ADDRESS
          - ip address 192.168.0.1 255.255.255.0
          - no shutdown
       

    - name: MOSTRAR LAS INTERFACES IPv4 
      ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: GUARDAR CONFIG ./ios_configurations/
      copy:
        content: "{{ output.stdout[0]}}"
        dest: "ios_configurations/IPv4_output_{{inventory_hostname}}.txt"
